# Generated by Django 4.2.5 on 2023-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
