# Generated by Django 4.2.5 on 2023-11-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_options_book_date_added_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-date_added', 'author'), 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
    ]
