# Generated by Django 4.2.5 on 2023-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AddField(
            model_name='book',
            name='label',
            field=models.ImageField(blank=True, default='', upload_to='label'),
        ),
    ]
