# Generated by Django 4.2.5 on 2024-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_history_options_book_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
